version: '3'

networks:
  wordpress_network:
    driver: bridge

services:
  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    command: "--server-id=1 --log-bin=mysql-bin --binlog-do-db=wordpress"
    environment:
      MYSQL_ROOT_PASSWORD: A123456
      MYSQL_DATABASE: dbmaster
    ports:
      - "3307:3306" 
    networks:
      - wordpress_network

  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    command: "--server-id=2 --log-bin=mysql-bin --binlog-do-db=wordpress"
    environment:
      MYSQL_ROOT_PASSWORD: A123456
      MYSQL_DATABASE: dbslave
    networks:
      - wordpress_network
    depends_on:
      - mysql_master

  wordpress1:
    image: wordpress
    container_name: wordpress1
    depends_on:
      - mysql_master
    ports:
      - "81:80"
    networks:
      - wordpress_network

  wordpress2:
    image: wordpress
    container_name: wordpress2
    depends_on:
      - mysql_master
    ports:
      - "82:80"
    networks:
      - wordpress_network

  wordpress3:
    image: wordpress
    container_name: wordpress3
    depends_on:
      - mysql_master
    ports:
      - "83:80"
    networks:
      - wordpress_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOSTS: mysql_master, mysql_slave
      MYSQL_ROOT_PASSWORD: 12345
    depends_on:
      - mysql_master
      - mysql_slave
    networks:
      - wordpress_network
